name: Build Android APK
on:
  push:
    branches: [ "73.0.3683.93" ]
  pull_request:
    branches: [ "73.0.3683.93" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        cmdline-tools-version: '8.0'

    - name: Accept Android licenses
      run: |
        yes | sdkmanager --licenses
        sdkmanager "build-tools;30.0.3" "platforms;android-30"

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Clean project
      run: ./gradlew clean

    - name: Build debug APK
      run: ./gradlew :app:assembleDebug --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/*.apk

    - name: Upload Build Reports
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: build-reports
        path: |
          app/build/reports/
          */build/reports/
